<a href="https://colab.research.google.com/github/dishibhatt05/ML_tasks/blob/data_processing/prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as n

In [0]:
a=input("enter array")
a=n.array(a)
print(a)

enter array[[1,2],[3,4]]
[[1,2],[3,4]]


In [0]:
import random as r

In [0]:
n.random.random((3,2))

array([[0.82005486, 0.61219744],
       [0.93846759, 0.26666605],
       [0.93239485, 0.06125835]])

In [0]:
[[random.random() for x in xrange(5)] for y in xrange(4)]

In [0]:
x=n.random.random((3,2))
y=n.random.random((2,5))

In [0]:
x


array([[0.16148954, 0.20465613],
       [0.80644619, 0.40605573],
       [0.36607056, 0.06702076]])

In [0]:
y

array([[0.58646271, 0.02439438, 0.18264678, 0.63062653, 0.16636884],
       [0.78262397, 0.77461313, 0.91624255, 0.42099504, 0.11303438]])

In [0]:
#from tempfile import TemporaryFile
#file1=TemporaryFile()
n.save(file1,x)
file1.seek(0)
n.load(file1)

array([[0.16148954, 0.20465613],
       [0.80644619, 0.40605573],
       [0.36607056, 0.06702076]])

In [0]:
sampl = n.random.uniform(low=0, high=10, size=(10,))
sampl

array([2.24555194, 3.43962391, 3.86567563, 8.24058919, 0.92736734,
       6.56615229, 7.71331392, 2.27418781, 3.93568106, 8.98980824])

In [0]:
import itertools

for item in itertools.permutations(x.reshape(2), 2):
    print(n.array(item).reshape(3,3))